server:
  port: 10090
spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: 10.253.48.53:9092
    #    bootstrap-servers: 10.243.141.63:9092
    producer:
      acks: 1
      batch-size: 16384
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 消息的 value 的序列化
    consumer:
      properties:
        group:
          id: quant
      enable-auto-commit: true
      auto-offset-reset: latest
      max-poll-records: 5000
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      type: batch
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always

