server:
  port: 8091
spring:
  application:
    name: kingstar-gold
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-timeout: 10s
        health-check-interval: 10s
        prefer-ip-address: true
        instance-id: ${spring.application.name}
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB
      max-request-size: 100MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
logging:
  file:
    max-size: 10MB
    max-history: 7
    name: /data/gold/gold.log
  level:
    com.kingstar.gold.mapper: DEBUG

mybatis:
  mapper-locations: classpath:mapping/*.xml



minio:
  request:
    url: http://10.253.48.53:9000
    bucket-name: gold-dev
    access-key: AKIAIOSFODNN7EXAMPLE
    secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  response:
    url: http://10.253.48.53/data



